version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: continum
      MYSQL_PASSWORD: Continum_123
      MYSQL_DATABASE: attendance
      MYSQL_ROOT_PASSWORD: Continum_123
    # volumes:
    #   - ./mysqldata:/var/lib/mysql/data
    # left is expose, right in container
    ports:
      - '3307:3306'
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    network_mode: "host"
    env_file:
      - ./backend/.env.docker
  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - '80:80'
    env_file:
      - ./frontend/.env.docker
  