declare module 'jsonwebtoken';
declare module 'vue-the-mask';
declare module 'vuelidate/lib/validators';
declare module 'vuelidate';
declare module 'papaparse';
declare module 'v-currency-field';
declare module 'jspdf';
declare module 'vue2-timepicker';
declare module '@develoka/angka-terbilang-js';
